perf: add eval to function map
casbin/casbin pull request #1005
Opened 2022-05-05 12:41 UTC by abichinger

#1000 

Benchmark results:
```
Before:
BenchmarkABACRuleModel-12    	      49	  21753411 ns/op	 4408055 B/op	  100021 allocs/op

After:
BenchmarkABACRuleModel-12    	     165	   7101567 ns/op	 1320970 B/op	   40087 allocs/op
```

Signed-off-by: Andreas Bichinger <andreas.bichinger@gmail.com>

2022-05-05 13:19 UTC, hsluoyz commented
@tangyang9464

2022-05-09 10:26 UTC, tangyang9464 requested changes

2022-05-09 10:26 UTC, tangyang9464 commented on enforcer.go
> +			return nil, fmt.Errorf("Expected %d arguments, but got %d", 1, len(args))
Should be more accurately described，such as "Eval expected ......"

2022-05-09 10:26 UTC, tangyang9464 commented on enforcer.go
> +			return nil, errors.New("Argument must be a string")
Same as above

2022-05-10 13:10 UTC, tangyang9464 commented on enforcer.go
> +			return nil, fmt.Errorf("Error while parsing subrule: %s, %s", expression, err.Error())
I think the subrule is confusing, perhaps use ``eval parameter`` instead of subrule

2022-05-12 02:08 UTC, hsluoyz commented
@tangyang9464

2022-05-12 02:45 UTC, tangyang9464 approved these changes
LGTM

2022-05-12 10:38 UTC, merged

2022-05-12 10:39 UTC, hsluoyz commented
@abichinger good work! Can you also update the benchmark at: https://casbin.org/docs/en/benchmark ?