feat: add GetAllRolesInDomain
casbin/casbin pull request #1023
Opened 2022-06-01 11:48 UTC by peng19940915

add  function: GetAllRolesInDomain

2022-06-01 12:08 UTC, hsluoyz commented
@tangyang9464

2022-06-02 02:45 UTC, tangyang9464 requested changes

2022-06-02 02:45 UTC, tangyang9464 commented on management_api.go
> +func (e *Enforcer) GetAllRolesInDomain(domain string) []string {
@peng19940915 should be ``GetAllRolesInDomain(domain string, ptype string...)``. ptype is determined by the user, and if the user does not pass in ptype, to get all by default.

2022-06-02 06:29 UTC, hsluoyz commented
@peng19940915 are you applying for OSPP 2022? Please join QQ group: 482622336

2022-06-03 02:23 UTC, closed without merging