feat: refactor the LoadPolicy in SyncedEnforcer, reduce the lock range
casbin/casbin pull request #1109
Opened 2022-09-18 09:00 UTC by deagon

#1108

2022-09-18 09:01 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/casbin/casbin?pullRequest=1109) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/casbin/casbin?pullRequest=1109) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/casbin/casbin?pullRequest=1109) it.</sub>

2022-09-18 09:17 UTC, hsluoyz commented
@deagon what does this PR do?

2022-09-18 09:41 UTC, deagon commented
> @deagon what does this PR do?

@hsluoyz fix https://github.com/casbin/casbin/issues/1108

2022-09-18 10:23 UTC, hsluoyz commented
@JalinWang plz review

/cc @tangyang9464

2022-09-19 03:09 UTC, JalinWang commented
The pr is technically ok. However, when `LoadPolicy` is called, it indicates changes in policies. If the function starts without locking, there might be other enforcement requests using out-of-date policies.

2022-09-20 06:59 UTC, deagon commented
> The pr is technically ok. However, when `LoadPolicy` is called, it indicates changes in policies. If the function starts without locking, there might be other enforcement requests using out-of-date policies.

That's right. However, `LoadPolicy` costs almost 3 seconds in my production environment. The permission read requests would be blocked 3 seconds If it locks, which is unacceptable for us.
In this case, I think out-of-date policies might be ok.

2022-09-20 08:51 UTC, hsluoyz requested changes

2022-09-20 08:51 UTC, hsluoyz commented on enforcer_synced.go
>  func (e *SyncedEnforcer) LoadPolicy() error {
Define a new function named `LoadPolicyFast()` to hold your code

2022-09-20 11:42 UTC, deagon commented
@hsluoyz  Please take a review, thanks.

2022-09-20 11:48 UTC, hsluoyz approved these changes

2022-09-20 12:16 UTC, merged

2022-09-29 06:31 UTC, hsluoyz commented
@deagon hi, this is impressive PR! Plz join the QQ group: 540163681

2023-05-31 03:45 UTC, pinkyo commented
thanks a lot, it help us solved a global performance issue. we got 400k policy data in db, and a reload operation cost more than 10s.