feat: support json request for ABAC
casbin/casbin pull request #1277
Opened 2023-07-16 10:24 UTC by PokIsemaine

fix: https://github.com/casbin/casbin/issues/1272

2023-07-16 11:47 UTC, hsluoyz commented
@nengc plz review

2023-07-16 15:33 UTC, hsluoyz requested changes

2023-07-16 15:33 UTC, hsluoyz commented on enforcer.go
> +	"github.com/tidwall/gjson"
sort imports

2023-07-16 15:33 UTC, hsluoyz commented on model_test.go
> +	e.EnableAcceptJsonRequest(true)
Separate test case

2023-07-17 04:11 UTC, hsluoyz approved these changes

2023-07-17 04:12 UTC, merged

2023-07-17 05:58 UTC, nengc commented
@hsluoyz @PokIsemaine Tks guys, It works.