feat: add GetRolesForUserForAllDomains
casbin/casbin pull request #612
Opened 2020-09-25 15:40 UTC by 00LT00

#588

2020-09-25 18:02 UTC, 00LT00 commented
plz review @PhilippSeitz @hsluoyz @nodece

2020-09-28 08:01 UTC, PhilippSeitz requested changes

2020-09-28 08:01 UTC, PhilippSeitz commented on rbac/default-role-manager/role_manager.go
> +		role := value.(*Roles).createRole(name, rm.matchingFunc)
is the `matchingFunc` supposed to work already, like discussed here #588?

```
p, admin, *, read, allow
p, admin, *, write, allow
p, member, *, read, allow
p, trudy.custom, trudy_org, write, allow
p, trudy.custom, trudy_org, read, deny

g, alice, admin, alice_org
g, bob, member, alice_org
g, trudy, member, trudy_org
g, trudy, trudy.custom, trudy_org
```

```go
e, _ := casbin.NewEnforcer(config)
e.GetRoleManager().(*defaultrolemanager.RoleManager).AddMatchingFunc("keyMatch", util.KeyMatch)
result, err := e.GetImplicitPermissionsForUserForAllDomains(subject)
expected := [][]string{
	{"member", "trudy_org", "read", "allow"},
	{"trudy.custom", "trudy_org", "write", "allow"},
	{"trudy.custom", "trudy_org", "read", "deny"},
}
Expect(err).ShouldNot(HaveOccurred())
Expect(result).Should(ConsistOf(expected))
```

will result in:
```
  Expected
      <[][]string | len:2, cap:2>: [
          ["trudy.custom", "trudy_org", "write", "allow"],
          ["trudy.custom", "trudy_org", "read", "deny"],
      ]
  to consist of
      <[]interface {} | len:1, cap:1>: [
          [
              ["member", "trudy_org", "read", "allow"],
              ["trudy.custom", "trudy_org", "write", "allow"],
              ["trudy.custom", "trudy_org", "read", "deny"],
          ],
      ]
  the missing elements were
      <[]interface {} | len:1, cap:1>: [
          ["member", "trudy_org", "read", "allow"],
      ]
```

2020-09-29 13:22 UTC, hsluoyz commented
@00LT00 any update?

2020-12-18 01:56 UTC, hsluoyz commented
@00LT00 any update?

2021-02-20 11:42 UTC, closed without merging