fix: print stdout log without control
casbin/casbin pull request #630
Opened 2020-10-27 01:22 UTC by kocoler

- Fix print stdout log without control.
- Add logger control method.

2020-10-27 01:25 UTC, kocoler commented
Fix #629

2020-10-27 02:15 UTC, hsluoyz commented
@kocoler please fix DCO.

2020-10-28 00:34 UTC, hsluoyz commented
@kocoler plz make it draft if not ready

2020-10-28 07:32 UTC, kocoler commented
@hsluoyz plz review.

2020-10-28 11:23 UTC, hsluoyz requested changes
Please fix.

2020-10-28 11:23 UTC, hsluoyz commented on log/default_logger.go
> +	enable bool
enabled

2020-10-28 11:23 UTC, hsluoyz commented on enforcer.go
> +	//log.GetLogger().EnableLog(enable)
Remove all comments.

2020-10-28 11:23 UTC, hsluoyz commented on enforcer.go
> +	e.rm.SetRMLogger(e.logger)
Change ALL to SetLogger, GetLogger

2020-10-28 11:23 UTC, hsluoyz commented on model/model.go
> +	for _, v := range model {
This code is so ugly, please change.

2020-10-29 01:53 UTC, hsluoyz commented on enforcer.go
> +func (e *Enforcer) GetLoggerEnableStatus() bool {
GetLoggerEnabled

2020-10-29 04:57 UTC, hsluoyz approved these changes
lgtm

2020-10-29 04:58 UTC, merged