feat:add priority support(#550)
casbin/casbin pull request #714
Opened 2021-02-21 07:16 UTC by closetool

Signed-off-by: closetool <c299999999@qq.com>

Fix: #550 

method `UpdatePolicy` not support priority yet

2021-02-21 08:49 UTC, hsluoyz commented
@closetool plz fix semantic PR:

![image](https://user-images.githubusercontent.com/3787410/108620124-d12ef800-7464-11eb-8177-b9beb23cb883.png)

2021-02-22 09:12 UTC, closetool commented
@hsluoyz plz review

2021-02-22 11:04 UTC, hsluoyz commented
@wndrr101 please review.

2021-02-27 15:21 UTC, nodece commented on enforcer.go
> +	if err := e.model.SortPoliciesByPriority(); err != nil {
Unnecessary code.

2021-02-27 15:26 UTC, nodece requested changes
You need to format code after completing the changes.

2021-03-01 06:36 UTC, closetool commented
@nodece plz review again

2021-03-01 07:01 UTC, merged