fix: remove default role manager domain map
casbin/casbin pull request #724
Opened 2021-03-07 06:51 UTC by closetool

Signed-off-by: closetool <c299999999@qq.com>

2021-03-07 15:17 UTC, closetool commented
@hsluoyz plz review

2021-03-07 15:58 UTC, hsluoyz requested changes

2021-03-07 15:58 UTC, hsluoyz commented on rbac/default-role-manager/role_manager.go
> +const defaultDomain string = "casbin_default"
Why `defaultDomain` is not empty string?

I think a global user alice should be ``::alice``

2021-03-08 05:14 UTC, hsluoyz commented
@closetool can you post the comparison data of our benchmark test: https://casbin.org/docs/en/benchmark ?

2021-03-08 05:14 UTC, hsluoyz approved these changes

2021-03-08 11:58 UTC, hsluoyz commented
The performance diff:

![image](https://user-images.githubusercontent.com/3787410/110318594-a211ac80-8048-11eb-9ddb-2e292122c8ad.png)

2021-03-08 11:58 UTC, merged