fix: GetPermissionsForUesr retrives empty policy
casbin/casbin pull request #770
Opened 2021-04-22 08:29 UTC by closetool

Signed-off-by: closetool <c299999999@qq.com>

Fix: #767

2021-04-22 12:59 UTC, hsluoyz commented
@sagarshah1983 plz review.

2021-04-23 02:43 UTC, sagarshah1983 commented
Thank you for getting this fixed.

2021-04-23 02:43 UTC, sagarshah1983 approved these changes
Thanks @closetool / @hsluoyz

2021-04-23 03:29 UTC, hsluoyz requested changes
retrives -> retrieves

2021-04-23 03:29 UTC, hsluoyz commented on rbac_api.go
> +	"fmt"
empty line

2021-04-23 03:38 UTC, hsluoyz approved these changes

2021-04-23 03:38 UTC, merged