fix: error parameter in GetUsers at default role manager
casbin/casbin pull request #794
Opened 2021-05-17 15:43 UTC by Sagilio

2021-05-17 16:16 UTC, hsluoyz commented
@closetool

2021-05-24 02:06 UTC, hsluoyz commented
@closetool plz review.

2021-05-24 02:06 UTC, hsluoyz requested changes
plz fix:

![image](https://user-images.githubusercontent.com/3787410/119286807-c52b2000-bc77-11eb-99fc-c611c3af38b6.png)

2021-05-24 02:45 UTC, hsluoyz approved these changes

2021-05-24 07:00 UTC, closetool approved these changes
LGTM

2021-05-24 08:32 UTC, merged