fix: lost model data if LoadPolicy failed
casbin/casbin pull request #823
Opened 2021-06-25 06:27 UTC by closetool

Signed-off-by: closetool <c299999999@qq.com>

Fix: #820 #791

2021-06-25 08:37 UTC, hsluoyz commented
@elissa2333 @hiteshsethi plz review

2021-06-25 12:52 UTC, nodece approved these changes
LGTM

2021-06-28 05:01 UTC, closetool commented
@hsluoyz @elissa2333 @hiteshsethi

2021-07-01 08:25 UTC, hsluoyz requested changes

2021-07-01 08:25 UTC, hsluoyz commented on enforcer.go
> +	built := false
Change to `needToRebuild`

2021-07-01 08:25 UTC, hsluoyz commented on model/assertion.go
> +}
new line

2021-07-01 08:25 UTC, hsluoyz commented on model/model.go
> +}
new line

2021-07-01 09:01 UTC, merged