fix: filter not support mutiple ptype
casbin/casbin pull request #826
Opened 2021-06-30 03:01 UTC by closetool

Signed-off-by: closetool <c299999999@qq.com>

Fix: #825

2021-06-30 03:02 UTC, closetool commented
@hsluoyz @Zxilly

2021-06-30 03:29 UTC, Zxilly approved these changes
lgtm

2021-06-30 10:56 UTC, hsluoyz requested changes

2021-06-30 10:56 UTC, hsluoyz commented on persist/file-adapter/adapter_filtered.go
> +	PG map[string][][]string
This is a breaking change. At least we should use "feature:" instead of "fix:"

2021-06-30 10:56 UTC, hsluoyz commented on filter_test.go
> +	"github.com/casbin/casbin/v2/util"
sort

2021-06-30 10:56 UTC, hsluoyz commented on filter_test.go
> +		PG: map[string][][]string{
A way to keep compatibility:

```go
	if err := e.LoadFilteredPolicy(&fileadapter.Filter{
		P: []string{"", "domain1"},
		G: []string{"", "", "domain1"},
		G2: []string{"", "", "domain1"},
		G3: []string{"", "", "domain1"},
	}); err != nil {
		t.Errorf("unexpected error in LoadFilteredPolicy: %v", err)
	}
```

I think we can hard-code it to G4 or G5. It's enough to use.

2021-06-30 10:57 UTC, hsluoyz commented on persist/file-adapter/adapter_filtered.go
> +	PG map[string][][]string
For: https://github.com/casbin/casbin/pull/826#discussion_r661350076, we can use fix:

2021-07-02 13:13 UTC, hsluoyz approved these changes

2021-07-02 13:16 UTC, merged