feat: add multiple policy support
casbin/casbin pull request #837
Opened 2021-07-11 06:01 UTC by tangyang9464

Signed-off-by: tangyang9464 <tangyang9464@163.com>

fix: #835

2021-07-11 10:53 UTC, sagilio requested changes
I think it better to use a new API or parameter to support multiple types.

Casbin.NET plans to use `EnforceContext` to support multiple types or custom types. https://github.com/casbin/Casbin.NET/blob/8a3f1fd2cdbc176ec018d9cec263fc51853ad1b8/NetCasbin/Extensions/Enforcer/EnforcerExtension.cs#L398-L406

2021-07-11 11:02 UTC, tangyang9464 commented on enforcer.go
>  	var expString string
you are right.Here should match with "r" as the prefix

2021-07-12 02:42 UTC, hsluoyz commented
@closetool plz review.

2021-07-12 10:36 UTC, tangyang9464 commented
There are some errors.I'll make a new PR

2021-07-12 10:37 UTC, closed without merging

2021-07-12 14:55 UTC, hsluoyz commented
Replaced by: https://github.com/casbin/casbin/pull/838