feat: support bracket with in operator
casbin/casbin pull request #866
Opened 2021-08-13 10:49 UTC by closetool

Signed-off-by: closetool <c299999999@qq.com>

Fix: #863

2021-08-13 11:25 UTC, hsluoyz commented
@closetool AT them to review

2021-08-13 12:53 UTC, closetool commented
@tangyang9464 @Zxilly please review

2021-08-13 13:20 UTC, Zxilly approved these changes
lgtm

2021-08-13 13:21 UTC, Zxilly commented
@closetool You can also add a unit test with `[]` grammar, to prevent potential break change in the future.

2021-08-13 13:21 UTC, tangyang9464 approved these changes
LGTM

2021-08-13 16:31 UTC, hsluoyz commented
> @closetool You can also add a unit test with `[]` grammar, to prevent potential breaking change in the future.

good point, @closetool

2021-08-14 03:57 UTC, closetool commented
@hsluoyz @Zxilly Added

2021-08-14 04:14 UTC, Zxilly requested changes

2021-08-14 04:14 UTC, Zxilly commented on examples/rbac_model_matcher_using_in_op_bracket.conf
> +m = g(r.sub, p.sub) && r.obj == p.obj && r.act == p.act || r.obj in ('data2', 'data3')
should be square bracket

2021-08-14 05:56 UTC, Zxilly requested changes

2021-08-14 05:56 UTC, Zxilly commented on main/go.mod
> +replace github.com/casbin/casbin/v2 => ../
Plz remove these files

2021-08-14 08:50 UTC, merged